accounts/urls.py
from django.conf.urls import patterns, include, url

from accounts import views

urlpatterns = patterns('',
    # Examples:
	url(r'^$', 'accounts.views.signup'),
    url(r'^signin/', 'accounts.views.signin', name='signin'),
	url(r'^signup', 'accounts.views.signup', name='signup'),
	url(r'^signout', 'accounts.views.signout_view', name='signout'),
    
)

global/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('home.urls')),
     url(r'^accounts/', include('accounts.urls',namespace="accounts")),
     url(r'^agent/', include('agent.urls',namespace="agent")),
     url(r'^track/', include('track.urls',namespace="track")),
url(r'^home/', include('home.urls')),

)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import patterns, include, url

from home import views
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'profilespoint.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'home.views.index', name='index'),

)

home/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
    


# Create your models here.
class UserExtended(models.Model):
        user = models.OneToOneField(User)
        role = models.CharField(max_length=15)

        def __unicode__(self):
                return self.brief_description, self.role

home/forms.py
from django import forms

home/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.http import HttpResponse



def index(request):
	return render(request, 'home/index.html')


	
	
	
	

home/templates/home/basic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cloud Tisa | Home</title>
	{% load staticfiles %}
    <!-- Bootstrap -->
    <link href="{% static "home/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<div class="container">
	{% block content %}
	{% endblock%}
	</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "home/js/jquery.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "home/js/bootstrap.min.js" %}"></script>
  </body>
</html>

home/templates/home/browse.html
{% extends 'home/nav_bar.html'%}
	
{% block body %}
{% for profile in view_profiles %}

	<div class="list-group">
  <a href="{% url 'profiles:view_one' profile.id %}" class="list-group-item">
    <h4 class="list-group-item-heading" align="center">{{profile.profiles_heading}}</h4>
    <p class="list-group-item-text">{{profile.introduction|truncatechars:185}}</p>
  </a>
</div>
<br>

{% endfor %}






{% endblock %}

home/templates/home/nav_bar.html
{% extends 'home/basic.html' %}
{% block page_content %}

</div>
{# closed the container div tag from the basic.html page so that the nav page can be broad #}

{% if user.is_authenticated %} 
	{# if the user is logged in then display the nav_bar #}
	<div class="navbar navbar-default">
	  <div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'main:index' %}">Profiles Point</a>
	  </div>
	  <div class="navbar-collapse collapse navbar-responsive-collapse">
		<ul class="nav navbar-nav">
		  <li class="active"><a href="#">Active</a></li>
		  <li><a href="#">Link</a></li>
		  <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Profiles <b class="caret"></b></a>
			<ul class="dropdown-menu">
			  <li><a href="{% url 'profiles:create' %}">Create a New Profile</a></li>
			  <li><a href="{% url 'profiles:view_all' %}#">View My Profiles</a></li>
			  <li><a href="#">Something else here</a></li>
			  <li class="divider"></li>
			  <li class="dropdown-header">Dropdown header</li>
			  <li><a href="#">Separated link</a></li>
			  <li><a href="#">One more separated link</a></li>
			</ul>
		  </li>
		</ul>
		<form class="navbar-form navbar-left">
		  <input type="text" class="form-control col-lg-8" placeholder="Search">
		</form>
		<ul class="nav navbar-nav navbar-right">
		  <li><a href="#">Link</a></li>
		  <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">You are signed in as {{user.username}}.<b class="caret"></b></a>
			<ul class="dropdown-menu">
			  <li><a href="#"></a></li>
			  <li><a href="#">Another action</a></li>
			  <li><a href="#">Something else here</a></li>
			  <li class="divider"></li>
			  <li><a href="{% url 'accounts:signout'%}">Sign Out</a></li>
			</ul>
		  </li>
		</ul>
	  </div>
	</div>
	<br><div class="container">


	</div>

{% else %}
{# the user has not logged so give option to sign in or sign up #}

	<br>
	<div class="container">
	<div align="right">
	<a href="{% url 'accounts:signin' %}" class="btn btn-info">Sign In </a>
	or 
	<a href="{% url 'accounts:signup' %}" class="btn btn-info">Sign Up Today </a>
	</div>
	</div>
	<br>
	<br>
	<br>

{% endif %}
{# display content either way i.e if the user is logged in or not #}

<div class="container">
	{% block body %}
	{% endblock %}

{% endblock%}